Sob bootstrap 1
GaloyMoney/galoy-infra pull request #43
Opened 2022-05-15 21:31 UTC by fireballpoint1

2022-05-16 05:31 UTC, krtk6160 commented
Please follow the conventional commits guidelines linked in [DEV.md](https://github.com/GaloyMoney/galoy/blob/main/DEV.md#contributing) for commit messages and PR titles

2022-06-03 05:16 UTC, sandipndev requested changes
I have tested the resources in this PR and both the apply and destroy phase worked! 
Please make the formatting changes and this PR should be ready to go in.

2022-06-03 05:16 UTC, sandipndev commented on modules/bootstrap/azure/variables.tf
> +variable "external_users" { default = [] }
Can you get rid of `external_users`, it doesn't look like it is needed here.

2022-06-03 05:16 UTC, sandipndev commented on modules/bootstrap/azure/tf-state-storage.tf
> +  name                     = "${local.name_prefix}sa"
any account name must be exported (added to outputs)

2022-06-03 05:16 UTC, sandipndev commented on modules/bootstrap/azure/resource-group.tf
> +}
please add a newline at the end. (EOLF)

2022-06-03 05:16 UTC, sandipndev commented on modules/bootstrap/azure/service-principal.tf
> +  inception_app_name = "${local.name_prefix}-inception-tf"
let's keep all the locals along with variables.tf

2022-06-16 07:32 UTC, sandipndev approved these changes

2022-06-16 07:33 UTC, merged